apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: davtro02
spec:
  replicas: 1
  selector: { matchLabels: { app: kafka-ui } }
  template:
    metadata: { labels: { app: kafka-ui } }
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - { name: KAFKA_CLUSTERS_0_NAME, value: davtro }
            - { name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS, value: "kafka-kraft:9092" }
          ports: [{ containerPort: 8080 }]
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits: { cpu: 500m, memory: 512Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: davtro02
spec:
  selector: { app: kafka-ui }
  ports: [{ port: 80, targetPort: 8080 }]
