# Wymaga Prometheus Operatora (CRD ServiceMonitor)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: davtro-services
  namespace: davtro02
  labels: { release: prometheus }
spec:
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [fastapi-web-app, postgres-exporter, kafka-exporter] }
  endpoints:
    - port: metrics
      interval: 15s
