apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml
- postgres.yaml
- redis.yaml
- vault.yaml
- kafka.yaml
- message-processor.yaml
- spring-app.yaml
- spark.yaml
- prometheus.yaml
- exporters.yaml
- grafana.yaml
- loki.yaml
- promtail.yaml
- tempo.yaml
- pgadmin.yaml
- kafka-ui.yaml
- network-policies.yaml
- ingress.yaml
- kyverno-policy.yaml
- service-monitors.yaml
- certificates.yaml

images:
- name: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01
  newName: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01
  newTag: 3e4abb5c0cd82ded66f4dc55644784f5c0bd1698
- name: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-consumer
  newName: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-consumer
  newTag: 3e4abb5c0cd82ded66f4dc55644784f5c0bd1698
- name: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-spark
  newName: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-spark
  newTag: 3e4abb5c0cd82ded66f4dc55644784f5c0bd1698
- name: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-spring
  newName: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-spring
  newTag: 3e4abb5c0cd82ded66f4dc55644784f5c0bd1698
