apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: davtro-secrets
  namespace: davtro02
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: davtro-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_USER
      remoteRef:
        key: db
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db
        property: DB_PASSWORD
    - secretKey: SMTP_USER
      remoteRef:
        key: smtp
        property: SMTP_USER
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: smtp
        property: SMTP_PASSWORD
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: auth
        property: ADMIN_PASSWORD
