# cert-manager + Vault PKI: root CA dla Istio (istiod) i certy dla Ingress Gateway.
# To NIE jest mTLS aplikacji - to jest CA dla control-plane Istio i TLS zewnetrzny.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault.davtro02.svc.cluster.local:8203
    path: pki/sign/davtro-ingress
    caProvider:
      type: Secret
      name: vault-tls
      key: ca.crt
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token
        key: token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer-internal
spec:
  vault:
    server: https://vault.davtro02.svc.cluster.local:8203
    path: pki/sign/davtro-internal
    caProvider:
      type: Secret
      name: vault-tls
      key: ca.crt
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token
        key: token
