apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: davtro02
spec:
  provider:
    vault:
      server: "https://vault.davtro02.svc.cluster.local:8203"
      path: "davtro"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-tls
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "davtro-apps"
          serviceAccountRef:
            name: "davtro-sa"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-dynamic
  namespace: davtro02
spec:
  provider:
    vault:
      server: "https://vault.davtro02.svc.cluster.local:8203"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-tls
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "davtro-apps"
          serviceAccountRef:
            name: "davtro-sa"
