apiVersion: v1
kind: ServiceAccount
metadata:
  name: davtro-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: message-processor-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-app-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-job-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-ui-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgadmin-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-exporter-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-exporter-sa
  namespace: davtro02
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-bootstrap-sa
  namespace: davtro02
