apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: davtro02-staging

resources:
  - ../../base

images:
  - name: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01
    newTag: staging
  - name: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-consumer
    newTag: staging
  - name: ghcr.io/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-sp01-spring
    newTag: staging

replicas:
  - name: fastapi-web-app
    count: 1
