apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: davtro
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sa
  namespace: davtro
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: message-processor-sa
  namespace: davtro
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-app-sa
  namespace: davtro
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: davtro
